-- G14-fixes: WirePlumber 0.4 Bluetooth monitor tweaks for the MT7925 adapter.
-- Installed to ~/.config/wireplumber/bluetooth.lua.d/ next to the stock
-- 50-bluez-config.lua (which this file amends, not replaces).
--
-- Disable mSBC (wideband HFP) for the headset microphone.
-- On the MediaTek MT7925 (USB 13d3:3602) with kernel 7.0 and the Poly
-- Voyager Legend 50, an mSBC call sets up its transparent eSCO link fine
-- (btmon: Synchronous Connect Complete, Air mode: Transparent) but the link
-- then carries no SCO data in either direction and is never disconnected.
-- Every following SCO setup to the headset is refused by the controller with
-- "Unsupported LMP Parameter Value (0x20)" until the headset's ACL link
-- drops, so most calls started with a dead microphone. Same on BT firmware
-- 20260813 and 20260605. With mSBC off, HFP negotiates CVSD: narrowband
-- (8 kHz, telephone quality) but 4 of 4 attempts worked with audio flowing
-- and clean teardown; HSP (no codec negotiation) worked 13 of 14.
-- Test: bash configs/bluetooth/bt-headset-mic-test.sh [-n 8]
bluez_monitor.properties["bluez5.enable-msbc"] = false
